# Skyseed Operations Monitoring
owner: billyus2025
repo: skyseed-upptime

sites:
  - name: EasyMathPrint
    url: https://easymathprint.com
  - name: EasyEnglishPrint
    url: https://easyenglishprint.com
  - name: EasySudokuPrint
    url: https://easysudokuprint.com
  - name: SkyseedLLC
    url: https://skyseed-llc.pages.dev

status-website:
  cname: ops.skyseedllc.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Skyseed Operations
  introTitle: "**Skyseed Operations** - Real-time monitoring for all Skyseed services"
  introMessage: Powered by Upptime, monitoring our services 24/7 with GitHub Actions
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Skyseed
      href: https://skyseedllc.com

# Update frequency
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 */6 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 */4 * * *"
  uptime: "*/5 * * * *"
